### PR TITLE
Manual Update.

### PR DESCRIPTION
**Pull request by leamas**
This PR updates the manual to recent boilerplate setup using simplified paths and default file names.  Here are also some minor formatting clean up. Only the manual directory is affected.

This  is a cleaned up version of #19 which is obsoleted by this one.

EDIT: It also makes the plugin start at heading level 0 to handle https://github.com/opencpn-manuals/plugins/issues/33

### CODE REVIEW

**Comment by leamas** [comment]
Rebased: Fixed bad commit comment in last commit.

**Comment by rgleason** [comment]
Alec, this wasn't accepted by Hannes unfortunately.  Maybe we can make another PR to him?

**Comment by leamas** [comment]
@rgleason: Please don't abuse this issue to communicate with me.

**Comment by leamas** [comment]
@Verezano : I was a bit surprised here. That you rejected this PR is certainly something you as repository owner can and should do from time to time, I have no problem with that  and do it myself regularly. The surprise is that you rejected without any comments at all, leaving me in the dark about possible problems.

To be honest, when I occasionally reject a PR without comments, it means that the submitter has made me **really** pissed for some reason. I hope that this is not the fact here.

Now, looking closer at the situation it seems that the PR did not apply after Rick's  last PR, and it thus needs to be rebased on the updated sources. I  will submit a new, rebased PR which applies. If you reject also this (again, something you could and should do on your discretion) please write a comment so I have a chance to fix possible problems

**Comment by leamas** [comment]
@Verenzano

Johan (a. k a. Verenzano) wrote:

> It seems that github confused me. After I merged Ricks PR I was no longer able to merge Alecs PR. Is it possible that Ricks PR contained everything in Alecs PR? By no means I want to decline your work on the documentation.

This is basically a mess. We first need to look forward to resolve the actual status the best possible way (or at least the least worse option). To that end I have updated the manual at https://github.com/opencpn-manuals/main so that it gets it's contents about the AISradar_pi plugin from this repository. That is, from now on you own the documentation, and any updates of the main manual wit respect to AISradar must be done in this repository. 

This is an important step, and it's taken. Let's  move on from that point after looking into why the current  repo is a mess in next post

**Comment by leamas** [comment]
@Verezano:

Some time ago you had two PR:s: this PR #20 from me, and #19 from Rick a k a @rgleason. I wrote this PR because #19 was in such a bad shape, and I presumed you you hesitated to merge it. For that reason I clearly stated this PR  obsoleted #19 in the [initial comment](https://github.com/Verezano/AISradar_pi/pull/20#issue-732112199)

That is, #19 was an extremely bad PR. When you merged you actually  imported a big mess of changes. Normally it's not a problem to back out changes like this, but in this case it's complicated enough to be avoided if you are not a seasoned git user.

#19 failed to meet some basic criterias for a PR:
  - A PR should  contain a description about what it does  which you  as the repo maintainer can understand.
  - A PR should be limited in scope w r t the description. The heading for 19 says that it updates index.adoc. In fact, it updates 27 (!) files, some of which outside the manual directory.
  - A PR should never, ever, contain merge commits. Full stop.

I would have rejected this PR for any of these points, What you have now is a really, really complicated mess in your history which is hard to rollback due to all merges.

As I see it, we could all learn of this:
  - I could have been even more clear in my initial description.
  - You  could have been a little more careful about readings the descriptions of the PRs before merging it.
  - Rick should learn to not file a PR  like this which fails basic requirements.
  - You could perhaps take some to review changes and see if they look sounde (after checking the basic requirement described above).

Sorry for long  post. In the end, repo is what it is, and we have to proceed from that point, hopefully without new   intermezzos like #19.

**Comment by rgleason** [comment]
You are a wonderful teacher Alec. It is just great to be on the same team with you.

**Comment by rgleason** [comment]
Alec, I have gone through your changes to the manual and checked them all.  I believe these changes are largely (except for one smalll one) in Hannes repository now.  

I have made changes and updated the PI frontend for TP version 1.0.176.1  and will be making a PR to Hannes for those changes and it will have that one small adjustment to the manual.  The plugin has been deployed to the Beta branch at present.

**Pull request closed without merging**
